<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Form1.cs" />
    <Compile Remove="Form1.Designer.cs" />
    <Compile Remove="Form2.cs" />
    <Compile Remove="Form2.Designer.cs" />
    <Compile Remove="Properties/**" />
    <EmbeddedResource Remove="**/*.resx" />
    <None Remove="Properties/**" />
  </ItemGroup>

</Project>